---
apache_server_name: "r1soft.awstask1.com"
apache_default_admin_email: "zhyldyzalova@gmail.com"
apache_copy_ssl_files: true
apache_ssl_certificate_file: 'files/vm.crt'
apache_ssl_certificate_key_file: 'files/vm.key'
# If apache_copy_ssl_files is false you need to provide the following variables:
# - apache_ssl_cert_file_location
# - apache_ssl_cert_key_location
apache_ssl_cert_file_location: "/etc/pki/tls/certs/vm.crt"
apache_ssl_cert_key_location: "/etc/pki/tls/private/vm.key"
apache_proxy_host: "localhost"
apache_proxy_port: 8080
default_context_path: "/"